name: build-and-deploy

on:
  push:
    branches:
      - main        # run on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build          # creates dist/

      - name: Upload to cPanel via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5   # <-- change v4 → v4.3.5

        with:
          server:     ${{ secrets.FTP_SERVER }}
          username:   ${{ secrets.FTP_USERNAME }}
          password:   ${{ secrets.FTP_PASSWORD }}
          protocol:   ftps
          local-dir:  dist/
          server-dir: ./      # chdange if your FTP user’s path differs
          dangerous-clean-slate: true
